import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Provider from "./Provider";  
import { ClerkProvider } from "@clerk/nextjs";
import { Mitr } from 'next/font/google'

const mitr = Mitr({
  weight:'300',
  subsets: ['latin', 'thai']
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${mitr.className} antialiased`}
        >
          <Provider>
            <Navbar></Navbar>
            <main className="container">{children}</main>

          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
